//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HDBH
    {
        public string SOHD { get; set; }
        public string MAHANG { get; set; }
        public string MALOAIHH { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string DVT { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
    
        public virtual HOADONBANHANG HOADONBANHANG { get; set; }
    }
}
