//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANGHOA()
        {
            this.HOADONBANHANGs = new HashSet<HOADONBANHANG>();
            this.HOADONNHAPHANGs = new HashSet<HOADONNHAPHANG>();
        }
    
        public string MAHANG { get; set; }
        public string TENHANG { get; set; }
        public string MALOAIHH { get; set; }
        public string MANCC { get; set; }
        public Nullable<decimal> GIABAN { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string DVT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONBANHANG> HOADONBANHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADONNHAPHANG> HOADONNHAPHANGs { get; set; }
        public virtual LOAIHANGHOA LOAIHANGHOA { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
