//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONNHAPHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONNHAPHANG()
        {
            this.CHITIET_HDNH = new HashSet<CHITIET_HDNH>();
        }
    
        public string SOHDNHAP { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public string NVNHAPHD { get; set; }
        public string MANCC { get; set; }
        public string MAHANG { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string DVT { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<double> GIAMGIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HDNH> CHITIET_HDNH { get; set; }
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
