//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONBANHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONBANHANG()
        {
            this.CHITIET_HDBH = new HashSet<CHITIET_HDBH>();
        }
    
        public string SOHD { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public string NVLAPHD { get; set; }
        public string MAKH { get; set; }
        public string MAHANG { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HDBH> CHITIET_HDBH { get; set; }
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
