//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLSTEntities : DbContext
    {
        public QLSTEntities()
            : base("name=QLSTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIET_HDBH> CHITIET_HDBH { get; set; }
        public virtual DbSet<CHITIET_HDNH> CHITIET_HDNH { get; set; }
        public virtual DbSet<HANGHOA> HANGHOAs { get; set; }
        public virtual DbSet<HOADONBANHANG> HOADONBANHANGs { get; set; }
        public virtual DbSet<HOADONNHAPHANG> HOADONNHAPHANGs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAIHANGHOA> LOAIHANGHOAs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int PR_KTKH(string mAKH, string sOHD)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            var sOHDParameter = sOHD != null ?
                new ObjectParameter("SOHD", sOHD) :
                new ObjectParameter("SOHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_KTKH", mAKHParameter, sOHDParameter);
        }
    
        public virtual int PR_SOLANMUAHANG(string mAKH, ObjectParameter sLMH)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_SOLANMUAHANG", mAKHParameter, sLMH);
        }
    
        public virtual int PR_SOLANNHAP(string mAHH, ObjectParameter sLN)
        {
            var mAHHParameter = mAHH != null ?
                new ObjectParameter("MAHH", mAHH) :
                new ObjectParameter("MAHH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_SOLANNHAP", mAHHParameter, sLN);
        }
    
        public virtual int PR_THONGTINHANGHOA(string mAHH, ObjectParameter sOLUONG, ObjectParameter gIABAN)
        {
            var mAHHParameter = mAHH != null ?
                new ObjectParameter("MAHH", mAHH) :
                new ObjectParameter("MAHH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_THONGTINHANGHOA", mAHHParameter, sOLUONG, gIABAN);
        }
    
        public virtual int PR_XEMKH(string mAKH, ObjectParameter tENKH, ObjectParameter dIACHI)
        {
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_XEMKH", mAKHParameter, tENKH, dIACHI);
        }
    
        public virtual int PR_XEMNCC(string mANCC, ObjectParameter tENNCC, ObjectParameter sDT, ObjectParameter dIACHI)
        {
            var mANCCParameter = mANCC != null ?
                new ObjectParameter("MANCC", mANCC) :
                new ObjectParameter("MANCC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_XEMNCC", mANCCParameter, tENNCC, sDT, dIACHI);
        }
    
        public virtual int PR_XEMNGAYLAPHD(string mAHD, ObjectParameter nGAYLAPHD)
        {
            var mAHDParameter = mAHD != null ?
                new ObjectParameter("MAHD", mAHD) :
                new ObjectParameter("MAHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_XEMNGAYLAPHD", mAHDParameter, nGAYLAPHD);
        }
    
        public virtual int PR_XEMNGAYNHAPHH(string mANCC, ObjectParameter nGAYNHAPHH)
        {
            var mANCCParameter = mANCC != null ?
                new ObjectParameter("MANCC", mANCC) :
                new ObjectParameter("MANCC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_XEMNGAYNHAPHH", mANCCParameter, nGAYNHAPHH);
        }
    
        public virtual int PR_XEMNV(string mAHD, ObjectParameter tENNV)
        {
            var mAHDParameter = mAHD != null ?
                new ObjectParameter("MAHD", mAHD) :
                new ObjectParameter("MAHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_XEMNV", mAHDParameter, tENNV);
        }
    
        public virtual int PR_XEMTONGTIEN(string mAHD, ObjectParameter tONGTIEN)
        {
            var mAHDParameter = mAHD != null ?
                new ObjectParameter("MAHD", mAHD) :
                new ObjectParameter("MAHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_XEMTONGTIEN", mAHDParameter, tONGTIEN);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
